apiVersion: v1
kind: Service
metadata:
  name: lndngigs-service
spec:
  selector:
    app: lndngigs
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lndngigs
spec:
  selector:
    matchLabels:
      app: lndngigs
  replicas: 2
  template:
    metadata:
      labels:
        app: lndngigs
    spec:
      containers:
      - name: lndngigs
        image: 721446610795.dkr.ecr.eu-west-1.amazonaws.com/lndngigs:latest
        ports:
        - containerPort: 8000
